import Head from 'next/head'
import { CardItem } from '../components/card/cardItem'
import { InfoCard } from '../components/card/InfoCard/InfoCard'
import { MusicPlayer } from '../components/musicPlayer';
import { CardContainer, Header2} from '../style-components'

export default function Home({ topAlbums, artist }) {

  console.log(topAlbums)

  return (
    <div>
      <Head>
        <title>PepeLaRana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <InfoCard topAlbum={topAlbums[0]} artist={artist} />
        
        <Header2 color='#E86060' weight="bold">Resultados</Header2>

        <CardContainer>
          {topAlbums.map(music => (
            <li key={music.id}>
              <CardItem {...music} />
            </li>
          ))}
        </CardContainer>

        {/* <MusicPlayer>{parse(embebido.html)}</MusicPlayer> */}
        <MusicPlayer {...topAlbums}/>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:4000/api/default/data")
  const data = await res.json()
  console.log(data)

  return {
    props: {
      topAlbums: data.topAlbums,
      artist: data.artist
    }
  }
}
