import Head from 'next/head'
import { CardItem } from '../components/card/cardItem'
import { InfoCard } from '../components/card/InfoCard/InfoCard'
import { MusicPlayer } from '../components/musicPlayer';
import { CardContainer, Header2} from '../style-components'
import { usePlayMusicContext } from '../context/playMusicContext';

export default function Home({ topAlbums, artist }) {
  const { state } = usePlayMusicContext()

  return (
    <div>
      <Head>
        <title>
          {
            state.play ? "🎵" : "Home"
          }
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <InfoCard topAlbum={topAlbums[0]} artist={artist} />
        
        <Header2 color='#E86060' weight="bold">Top Albums</Header2>

        <CardContainer>
          {topAlbums.map(music => (
            <li key={music.id}>
              <CardItem 
                name={music.artist.name} 
                img={music.cover_medium} 
                {...music} 
              />
            </li>
          ))}
        </CardContainer>

        <MusicPlayer />
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/default")
  const data = await res.json()

  return {
    props: {
      topAlbums: data.topAlbums,
      artist: data.artist
    }
  }
}
