import Head from 'next/head'
import { CardItem } from '../components/card/cardItem'
import { CardContainer, Header2} from '../style-components'

export default function Home({ topAlbums }) {

  console.log(topAlbums)

  return (
    <div>
      <Head>
        <title>PepeLaRana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header2 color='#E86060' weight="bold">Resultados</Header2>

        <CardContainer>
          {topAlbums.map(music => (
            <li key={music.id}>
              <CardItem {...music} />
            </li>
          ))}
        </CardContainer>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:4000/api/default/data")
  const data = await res.json()
  console.log(data)

  return {
    props: {topAlbums: data.topAlbums}
  }
}
